FROM node:18-alpine AS builder
WORKDIR /app
COPY todo-app-frontend/package*.json ./
RUN npm install
COPY todo-app-frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80